# Generated by Django 6.0.6 on 2026-06-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_order_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
